/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>

#include "parapin.h"

#define INTERVAL_MS 10

static GtkWidget *window1;
static GtkImage *image;
unsigned long pin;
unsigned int interval;
static int is_high;

void do_work(void);
static gboolean timeout_func(gpointer data);

int
main (int argc, char *argv[])
{

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

//  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");
  add_pixmap_directory (".");

  gtk_rc_add_default_file("gtkrc");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  window1 = create_window1 ();
  gtk_widget_show (window1);

  if (argc > 1) {
    interval = strtoul(argv[1], (char **) NULL, 10);
  } else {
    interval = INTERVAL_MS;
  }
  pin = LP_PIN15;

  do_work();

  gtk_main ();

  return 0;
}

void do_work(void)
{
  GtkWidget *ptr;
  char buffer[80];

  if (pin_init_user(LPT1) < 0)
    exit(1);

  pin_input_mode(LP_DATA_PINS | LP_SWITCHABLE_PINS);

  /* following condition is addes so that we don't waste CPU time
   * adding image for same signal again and again
   */
  image = GTK_IMAGE(lookup_widget(window1, "image1"));

  if (pin_is_set(pin)) {
    is_high = 1;
    gtk_image_set_from_file(image, "red.png");
  } else {
    is_high = 0;
    gtk_image_set_from_file(image, "green.png");
  }

  sprintf(buffer,
      "<b>Interval: <span foreground=\"blue\">%u</span></b> ms",
      interval);
  ptr = lookup_widget(window1, "label3");
  gtk_label_set_markup(GTK_LABEL(ptr), buffer);

  gtk_timeout_add(interval, timeout_func, NULL);
}

static gboolean timeout_func(gpointer data)
{
  if (pin_is_set(pin)) {
    if (is_high) {
      return TRUE;
    } else {
      is_high = 1;
      fprintf(stderr, "pin status changed\n");
      gtk_image_set_from_file(image, "red.png");
    }
  } else {
    if (!is_high) {
      return TRUE;
    } else {
      is_high = 0;
      fprintf(stderr, "pin status changed\n");
      gtk_image_set_from_file(image, "green.png");
    }
  }
  return TRUE;
}
