/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GtkWidget *vbox1;
  GtkWidget *fixed1;
  GtkWidget *entry1;
  GtkWidget *label1;
  GtkWidget *frame1;
  GtkWidget *alignment1;
  GtkWidget *fixed2;
  GtkWidget *entry2;
  GtkWidget *entry3;
  GtkWidget *entry4;
  GtkWidget *label3;
  GtkWidget *label2;
  GtkWidget *label4;
  GtkWidget *label7;
  GtkWidget *entry5;
  GtkWidget *hseparator1;
  GtkWidget *label6;
  GtkWidget *hbuttonbox1;
  GtkWidget *button1;
  GtkWidget *button2;
  GtkWidget *label5;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window1), _("Manage Passwords"));
  gtk_window_set_position (GTK_WINDOW (window1), GTK_WIN_POS_CENTER);

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (window1), vbox1);

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_box_pack_start (GTK_BOX (vbox1), fixed1, TRUE, TRUE, 5);
  gtk_container_set_border_width (GTK_CONTAINER (fixed1), 10);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_fixed_put (GTK_FIXED (fixed1), entry1, 184, 16);
  gtk_widget_set_size_request (entry1, 158, 25);
  gtk_tooltips_set_tip (tooltips, entry1, _("Enter admin password here"), NULL);
  gtk_entry_set_max_length (GTK_ENTRY (entry1), 10);
  gtk_entry_set_visibility (GTK_ENTRY (entry1), FALSE);

  label1 = gtk_label_new (_("Current Admin Password"));
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed1), label1, 0, 16);
  gtk_widget_set_size_request (label1, 158, 22);
  gtk_label_set_use_markup (GTK_LABEL (label1), TRUE);

  frame1 = gtk_frame_new (NULL);
  gtk_widget_show (frame1);
  gtk_box_pack_start (GTK_BOX (vbox1), frame1, TRUE, TRUE, 6);
  gtk_container_set_border_width (GTK_CONTAINER (frame1), 5);
  gtk_frame_set_label_align (GTK_FRAME (frame1), 0.5, 0.5);

  alignment1 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (frame1), alignment1);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment1), 0, 0, 12, 0);

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (alignment1), fixed2);

  entry2 = gtk_entry_new ();
  gtk_widget_show (entry2);
  gtk_fixed_put (GTK_FIXED (fixed2), entry2, 176, 16);
  gtk_widget_set_size_request (entry2, 158, 25);
  gtk_tooltips_set_tip (tooltips, entry2, _("New admin password (keep blank for using previous value)"), NULL);
  gtk_entry_set_max_length (GTK_ENTRY (entry2), 10);
  gtk_entry_set_visibility (GTK_ENTRY (entry2), FALSE);
  gtk_entry_set_activates_default (GTK_ENTRY (entry2), TRUE);

  entry3 = gtk_entry_new ();
  gtk_widget_show (entry3);
  gtk_fixed_put (GTK_FIXED (fixed2), entry3, 176, 48);
  gtk_widget_set_size_request (entry3, 158, 25);
  gtk_tooltips_set_tip (tooltips, entry3, _("New Login Password (keep blank for using previous value)"), NULL);
  gtk_entry_set_max_length (GTK_ENTRY (entry3), 10);
  gtk_entry_set_visibility (GTK_ENTRY (entry3), FALSE);
  gtk_entry_set_activates_default (GTK_ENTRY (entry3), TRUE);

  entry4 = gtk_entry_new ();
  gtk_widget_show (entry4);
  gtk_fixed_put (GTK_FIXED (fixed2), entry4, 176, 80);
  gtk_widget_set_size_request (entry4, 158, 25);
  gtk_tooltips_set_tip (tooltips, entry4, _("New Add Stuff Password (keep blank for using previous value)"), NULL);
  gtk_entry_set_max_length (GTK_ENTRY (entry4), 10);
  gtk_entry_set_visibility (GTK_ENTRY (entry4), FALSE);
  gtk_entry_set_activates_default (GTK_ENTRY (entry4), TRUE);

  label3 = gtk_label_new (_("New Login Password"));
  gtk_widget_show (label3);
  gtk_fixed_put (GTK_FIXED (fixed2), label3, 0, 48);
  gtk_widget_set_size_request (label3, 160, 24);
  gtk_label_set_use_markup (GTK_LABEL (label3), TRUE);

  label2 = gtk_label_new (_("New Admin Password"));
  gtk_widget_show (label2);
  gtk_fixed_put (GTK_FIXED (fixed2), label2, 0, 16);
  gtk_widget_set_size_request (label2, 160, 24);
  gtk_label_set_use_markup (GTK_LABEL (label2), TRUE);

  label4 = gtk_label_new (_("New Add Stuff Password"));
  gtk_widget_show (label4);
  gtk_fixed_put (GTK_FIXED (fixed2), label4, 0, 80);
  gtk_widget_set_size_request (label4, 160, 24);

  label7 = gtk_label_new (_("New Edit Stuff Password"));
  gtk_widget_show (label7);
  gtk_fixed_put (GTK_FIXED (fixed2), label7, 0, 112);
  gtk_widget_set_size_request (label7, 160, 24);

  entry5 = gtk_entry_new ();
  gtk_widget_show (entry5);
  gtk_fixed_put (GTK_FIXED (fixed2), entry5, 176, 112);
  gtk_widget_set_size_request (entry5, 158, 25);
  gtk_tooltips_set_tip (tooltips, entry5, _("New Edit Stuff Password (keep blank for using previous value)"), NULL);
  gtk_entry_set_max_length (GTK_ENTRY (entry5), 10);
  gtk_entry_set_visibility (GTK_ENTRY (entry5), FALSE);
  gtk_entry_set_activates_default (GTK_ENTRY (entry5), TRUE);

  hseparator1 = gtk_hseparator_new ();
  gtk_widget_show (hseparator1);
  gtk_fixed_put (GTK_FIXED (fixed2), hseparator1, 8, 184);
  gtk_widget_set_size_request (hseparator1, 376, 16);

  label6 = gtk_label_new (_("Message"));
  gtk_widget_show (label6);
  gtk_fixed_put (GTK_FIXED (fixed2), label6, 0, 152);
  gtk_widget_set_size_request (label6, 384, 24);
  gtk_label_set_use_markup (GTK_LABEL (label6), TRUE);

  hbuttonbox1 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox1);
  gtk_fixed_put (GTK_FIXED (fixed2), hbuttonbox1, 96, 208);
  gtk_widget_set_size_request (hbuttonbox1, 248, 32);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox1), GTK_BUTTONBOX_SPREAD);

  button1 = gtk_button_new_from_stock ("gtk-close");
  gtk_widget_show (button1);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), button1);
  GTK_WIDGET_SET_FLAGS (button1, GTK_CAN_DEFAULT);

  button2 = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (button2);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), button2);
  GTK_WIDGET_SET_FLAGS (button2, GTK_CAN_DEFAULT);

  label5 = gtk_label_new (_("<b>Manage Passwords</b>"));
  gtk_widget_show (label5);
  gtk_frame_set_label_widget (GTK_FRAME (frame1), label5);
  gtk_label_set_use_markup (GTK_LABEL (label5), TRUE);

  g_signal_connect ((gpointer) window1, "delete_event",
                    G_CALLBACK (on_window10_delete_event),
                    NULL);
  g_signal_connect ((gpointer) entry1, "activate",
                    G_CALLBACK (on_entry1_activate),
                    NULL);
  g_signal_connect ((gpointer) button1, "clicked",
                    G_CALLBACK (on_button1_clicked),
                    NULL);
  g_signal_connect ((gpointer) button2, "clicked",
                    G_CALLBACK (on_button2_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");
  GLADE_HOOKUP_OBJECT (window1, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (window1, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (window1, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (window1, label1, "label1");
  GLADE_HOOKUP_OBJECT (window1, frame1, "frame1");
  GLADE_HOOKUP_OBJECT (window1, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (window1, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (window1, entry2, "entry2");
  GLADE_HOOKUP_OBJECT (window1, entry3, "entry3");
  GLADE_HOOKUP_OBJECT (window1, entry4, "entry4");
  GLADE_HOOKUP_OBJECT (window1, label3, "label3");
  GLADE_HOOKUP_OBJECT (window1, label2, "label2");
  GLADE_HOOKUP_OBJECT (window1, label4, "label4");
  GLADE_HOOKUP_OBJECT (window1, label7, "label7");
  GLADE_HOOKUP_OBJECT (window1, entry5, "entry5");
  GLADE_HOOKUP_OBJECT (window1, hseparator1, "hseparator1");
  GLADE_HOOKUP_OBJECT (window1, label6, "label6");
  GLADE_HOOKUP_OBJECT (window1, hbuttonbox1, "hbuttonbox1");
  GLADE_HOOKUP_OBJECT (window1, button1, "button1");
  GLADE_HOOKUP_OBJECT (window1, button2, "button2");
  GLADE_HOOKUP_OBJECT (window1, label5, "label5");
  GLADE_HOOKUP_OBJECT_NO_REF (window1, tooltips, "tooltips");

  gtk_widget_grab_default (button2);
  return window1;
}

