#!/bin/sh

DB_DIR="$HOME/.attendence_db"
DB_NAME="auth.sdb"
DB="$DB_DIR/$DB_NAME"
TBL="passwd"

PASS="password"

TYPE_PASS_ADMIN=1
ADMIN_PASS="$PASS"
TYPE_PASS_ENTRY=2
ENTRY_PASS="$PASS"
TYPE_PASS_ADD=3
ADD_PASS="$PASS"
TYPE_PASS_EDIT=4
EDIT_PASS="$PASS"

mkdir -p $DB_DIR

sqlite3 $DB <<EOF
DROP TABLE $TBL;
CREATE TABLE $TBL (type INTEGER PRIMARY KEY, pass TEXT NOT NULL);
INSERT INTO $TBL VALUES ($TYPE_PASS_ADMIN, '$ADMIN_PASS');
INSERT INTO $TBL VALUES ($TYPE_PASS_ENTRY, '$ENTRY_PASS');
INSERT INTO $TBL VALUES ($TYPE_PASS_ADD, '$ADD_PASS');
INSERT INTO $TBL VALUES ($TYPE_PASS_EDIT, '$EDIT_PASS');
EOF

