/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GdkPixbuf *window1_icon_pixbuf;
  GtkWidget *vbox1;
  GtkWidget *menubar1;
  GtkWidget *menuitem1;
  GtkWidget *menuitem1_menu;
  GtkWidget *quit1;
  GtkWidget *menuitem4;
  GtkWidget *menuitem4_menu;
  GtkWidget *about1;
  GtkWidget *toolbar1;
  GtkIconSize tmp_toolbar_icon_size;
  GtkWidget *toolbutton1;
  GtkWidget *separatortoolitem1;
  GtkWidget *toolbutton3;
  GtkWidget *toolbutton4;
  GtkWidget *separatortoolitem2;
  GtkWidget *toolbutton5;
  GtkWidget *separatortoolitem3;
  GtkWidget *toolbutton6;
  GtkWidget *toolbutton7;
  GtkWidget *separatortoolitem4;
  GtkWidget *toolbutton8;
  GtkWidget *fixed1;
  GtkWidget *frame1;
  GtkWidget *hbox4;
  GtkWidget *label16;
  GtkWidget *arrow1;
  GtkWidget *image6;
  GtkWidget *label1;
  GtkWidget *label6;
  GtkWidget *scrolledwindow1;
  GtkWidget *treeview1;
  GtkWidget *hseparator1;
  GtkWidget *hbuttonbox1;
  GtkWidget *button1;
  GtkWidget *button2;
  GtkWidget *button17;
  GtkAccelGroup *accel_group;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  accel_group = gtk_accel_group_new ();

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window1), _("Attendance Monitoring System"));
  gtk_window_set_position (GTK_WINDOW (window1), GTK_WIN_POS_CENTER);
  window1_icon_pixbuf = create_pixbuf ("appicon_36x36.png");
  if (window1_icon_pixbuf)
    {
      gtk_window_set_icon (GTK_WINDOW (window1), window1_icon_pixbuf);
      gdk_pixbuf_unref (window1_icon_pixbuf);
    }

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (window1), vbox1);

  menubar1 = gtk_menu_bar_new ();
  gtk_widget_show (menubar1);
  gtk_box_pack_start (GTK_BOX (vbox1), menubar1, FALSE, FALSE, 0);

  menuitem1 = gtk_menu_item_new_with_mnemonic (_("_File"));
  gtk_widget_show (menuitem1);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem1);

  menuitem1_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem1), menuitem1_menu);

  quit1 = gtk_image_menu_item_new_from_stock ("gtk-quit", accel_group);
  gtk_widget_show (quit1);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), quit1);
  gtk_tooltips_set_tip (tooltips, quit1, _("Quit system"), NULL);

  menuitem4 = gtk_menu_item_new_with_mnemonic (_("_Help"));
  gtk_widget_show (menuitem4);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem4);

  menuitem4_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem4), menuitem4_menu);

  about1 = gtk_image_menu_item_new_from_stock ("gtk-about", accel_group);
  gtk_widget_show (about1);
  gtk_container_add (GTK_CONTAINER (menuitem4_menu), about1);
  gtk_tooltips_set_tip (tooltips, about1, _("About the author"), NULL);

  toolbar1 = gtk_toolbar_new ();
  gtk_widget_show (toolbar1);
  gtk_box_pack_start (GTK_BOX (vbox1), toolbar1, FALSE, FALSE, 0);
  gtk_toolbar_set_style (GTK_TOOLBAR (toolbar1), GTK_TOOLBAR_ICONS);
  tmp_toolbar_icon_size = gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar1));

  toolbutton1 = (GtkWidget*) gtk_tool_button_new_from_stock ("gtk-quit");
  gtk_widget_show (toolbutton1);
  gtk_container_add (GTK_CONTAINER (toolbar1), toolbutton1);
  gtk_tool_item_set_tooltip (GTK_TOOL_ITEM (toolbutton1), tooltips, _("Quit system"), NULL);

  separatortoolitem1 = (GtkWidget*) gtk_separator_tool_item_new ();
  gtk_widget_show (separatortoolitem1);
  gtk_container_add (GTK_CONTAINER (toolbar1), separatortoolitem1);

  toolbutton3 = (GtkWidget*) gtk_tool_button_new_from_stock ("gtk-add");
  gtk_widget_show (toolbutton3);
  gtk_container_add (GTK_CONTAINER (toolbar1), toolbutton3);
  gtk_tool_item_set_tooltip (GTK_TOOL_ITEM (toolbutton3), tooltips, _("Add Stuff"), NULL);

  toolbutton4 = (GtkWidget*) gtk_tool_button_new_from_stock ("gtk-edit");
  gtk_widget_show (toolbutton4);
  gtk_container_add (GTK_CONTAINER (toolbar1), toolbutton4);
  gtk_tool_item_set_tooltip (GTK_TOOL_ITEM (toolbutton4), tooltips, _("Edit Stuff Information"), NULL);

  separatortoolitem2 = (GtkWidget*) gtk_separator_tool_item_new ();
  gtk_widget_show (separatortoolitem2);
  gtk_container_add (GTK_CONTAINER (toolbar1), separatortoolitem2);

  toolbutton5 = (GtkWidget*) gtk_tool_button_new_from_stock ("gtk-execute");
  gtk_widget_show (toolbutton5);
  gtk_container_add (GTK_CONTAINER (toolbar1), toolbutton5);
  gtk_tool_item_set_tooltip (GTK_TOOL_ITEM (toolbutton5), tooltips, _("Extended Query"), NULL);

  separatortoolitem3 = (GtkWidget*) gtk_separator_tool_item_new ();
  gtk_widget_show (separatortoolitem3);
  gtk_container_add (GTK_CONTAINER (toolbar1), separatortoolitem3);

  toolbutton6 = (GtkWidget*) gtk_tool_button_new_from_stock ("gtk-convert");
  gtk_widget_show (toolbutton6);
  gtk_container_add (GTK_CONTAINER (toolbar1), toolbutton6);
  gtk_tool_item_set_tooltip (GTK_TOOL_ITEM (toolbutton6), tooltips, _("Show barcode entry window"), NULL);

  toolbutton7 = (GtkWidget*) gtk_tool_button_new_from_stock ("gtk-media-record");
  gtk_widget_show (toolbutton7);
  gtk_container_add (GTK_CONTAINER (toolbar1), toolbutton7);
  gtk_tool_item_set_tooltip (GTK_TOOL_ITEM (toolbutton7), tooltips, _("View last unmindful stuffs"), NULL);

  separatortoolitem4 = (GtkWidget*) gtk_separator_tool_item_new ();
  gtk_widget_show (separatortoolitem4);
  gtk_container_add (GTK_CONTAINER (toolbar1), separatortoolitem4);

  toolbutton8 = (GtkWidget*) gtk_tool_button_new_from_stock ("gtk-index");
  gtk_widget_show (toolbutton8);
  gtk_container_add (GTK_CONTAINER (toolbar1), toolbutton8);
  gtk_tool_item_set_tooltip (GTK_TOOL_ITEM (toolbutton8), tooltips, _("First IN Last OUT Query"), NULL);

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_box_pack_start (GTK_BOX (vbox1), fixed1, FALSE, TRUE, 0);
  gtk_widget_set_size_request (fixed1, -1, 410);

  frame1 = gtk_frame_new (NULL);
  gtk_widget_show (frame1);
  gtk_fixed_put (GTK_FIXED (fixed1), frame1, 0, 0);
  gtk_widget_set_size_request (frame1, 1008, 368);
  gtk_frame_set_label_align (GTK_FRAME (frame1), 0.5, 0.5);

  hbox4 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (frame1), hbox4);

  label16 = gtk_label_new (_("<b>Last Status</b>"));
  gtk_widget_show (label16);
  gtk_box_pack_start (GTK_BOX (hbox4), label16, TRUE, TRUE, 0);
  gtk_widget_set_size_request (label16, 370, -1);
  gtk_label_set_use_markup (GTK_LABEL (label16), TRUE);

  arrow1 = gtk_arrow_new (GTK_ARROW_RIGHT, GTK_SHADOW_OUT);
  gtk_widget_show (arrow1);
  gtk_box_pack_start (GTK_BOX (hbox4), arrow1, FALSE, TRUE, 0);

  image6 = create_pixmap (window1, NULL);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox4), image6, TRUE, TRUE, 0);

  label1 = gtk_label_new (_("<b>Stuff Status</b>"));
  gtk_widget_show (label1);
  gtk_frame_set_label_widget (GTK_FRAME (frame1), label1);
  gtk_label_set_use_markup (GTK_LABEL (label1), TRUE);

  label6 = gtk_label_new (_("<b>Today's Attendance History</b>"));
  gtk_widget_show (label6);
  gtk_fixed_put (GTK_FIXED (fixed1), label6, 256, 376);
  gtk_widget_set_size_request (label6, 432, 24);
  gtk_label_set_use_markup (GTK_LABEL (label6), TRUE);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_box_pack_start (GTK_BOX (vbox1), scrolledwindow1, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow1), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow1), GTK_SHADOW_IN);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), treeview1);
  gtk_tree_view_set_rules_hint (GTK_TREE_VIEW (treeview1), TRUE);
  gtk_tree_view_set_fixed_height_mode (GTK_TREE_VIEW (treeview1), TRUE);

  hseparator1 = gtk_hseparator_new ();
  gtk_widget_show (hseparator1);
  gtk_box_pack_start (GTK_BOX (vbox1), hseparator1, FALSE, TRUE, 0);
  gtk_widget_set_size_request (hseparator1, -1, 20);

  hbuttonbox1 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox1);
  gtk_box_pack_start (GTK_BOX (vbox1), hbuttonbox1, FALSE, TRUE, 5);
  gtk_container_set_border_width (GTK_CONTAINER (hbuttonbox1), 5);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox1), GTK_BUTTONBOX_SPREAD);

  button1 = gtk_button_new_from_stock ("gtk-quit");
  gtk_widget_show (button1);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), button1);
  GTK_WIDGET_SET_FLAGS (button1, GTK_CAN_DEFAULT);
  gtk_tooltips_set_tip (tooltips, button1, _("Quit system"), NULL);

  button2 = gtk_button_new_from_stock ("gtk-refresh");
  gtk_widget_show (button2);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), button2);
  GTK_WIDGET_SET_FLAGS (button2, GTK_CAN_DEFAULT);
  gtk_tooltips_set_tip (tooltips, button2, _("Refresh attendence list"), NULL);

  button17 = gtk_button_new_from_stock ("gtk-print");
  gtk_widget_show (button17);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), button17);
  GTK_WIDGET_SET_FLAGS (button17, GTK_CAN_DEFAULT);
  gtk_tooltips_set_tip (tooltips, button17, _("Print today's attendence list"), NULL);

  g_signal_connect ((gpointer) window1, "delete_event",
                    G_CALLBACK (on_window1_delete_event),
                    NULL);
  g_signal_connect ((gpointer) quit1, "activate",
                    G_CALLBACK (on_quit1_activate),
                    NULL);
  g_signal_connect ((gpointer) about1, "activate",
                    G_CALLBACK (on_about1_activate),
                    NULL);
  g_signal_connect ((gpointer) toolbutton1, "clicked",
                    G_CALLBACK (on_toolbutton1_clicked),
                    NULL);
  g_signal_connect ((gpointer) toolbutton3, "clicked",
                    G_CALLBACK (on_toolbutton3_clicked),
                    NULL);
  g_signal_connect ((gpointer) toolbutton4, "clicked",
                    G_CALLBACK (on_toolbutton4_clicked),
                    NULL);
  g_signal_connect ((gpointer) toolbutton5, "clicked",
                    G_CALLBACK (on_toolbutton5_clicked),
                    NULL);
  g_signal_connect ((gpointer) toolbutton6, "clicked",
                    G_CALLBACK (on_toolbutton6_clicked),
                    NULL);
  g_signal_connect ((gpointer) toolbutton7, "clicked",
                    G_CALLBACK (on_toolbutton7_clicked),
                    NULL);
  g_signal_connect ((gpointer) toolbutton8, "clicked",
                    G_CALLBACK (on_toolbutton8_clicked),
                    NULL);
  g_signal_connect ((gpointer) treeview1, "row_activated",
                    G_CALLBACK (on_treeview1_row_activated),
                    NULL);
  g_signal_connect ((gpointer) button1, "clicked",
                    G_CALLBACK (on_button1_clicked),
                    NULL);
  g_signal_connect ((gpointer) button2, "clicked",
                    G_CALLBACK (on_button2_clicked),
                    NULL);
  g_signal_connect ((gpointer) button17, "clicked",
                    G_CALLBACK (on_button17_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");
  GLADE_HOOKUP_OBJECT (window1, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (window1, menubar1, "menubar1");
  GLADE_HOOKUP_OBJECT (window1, menuitem1, "menuitem1");
  GLADE_HOOKUP_OBJECT (window1, menuitem1_menu, "menuitem1_menu");
  GLADE_HOOKUP_OBJECT (window1, quit1, "quit1");
  GLADE_HOOKUP_OBJECT (window1, menuitem4, "menuitem4");
  GLADE_HOOKUP_OBJECT (window1, menuitem4_menu, "menuitem4_menu");
  GLADE_HOOKUP_OBJECT (window1, about1, "about1");
  GLADE_HOOKUP_OBJECT (window1, toolbar1, "toolbar1");
  GLADE_HOOKUP_OBJECT (window1, toolbutton1, "toolbutton1");
  GLADE_HOOKUP_OBJECT (window1, separatortoolitem1, "separatortoolitem1");
  GLADE_HOOKUP_OBJECT (window1, toolbutton3, "toolbutton3");
  GLADE_HOOKUP_OBJECT (window1, toolbutton4, "toolbutton4");
  GLADE_HOOKUP_OBJECT (window1, separatortoolitem2, "separatortoolitem2");
  GLADE_HOOKUP_OBJECT (window1, toolbutton5, "toolbutton5");
  GLADE_HOOKUP_OBJECT (window1, separatortoolitem3, "separatortoolitem3");
  GLADE_HOOKUP_OBJECT (window1, toolbutton6, "toolbutton6");
  GLADE_HOOKUP_OBJECT (window1, toolbutton7, "toolbutton7");
  GLADE_HOOKUP_OBJECT (window1, separatortoolitem4, "separatortoolitem4");
  GLADE_HOOKUP_OBJECT (window1, toolbutton8, "toolbutton8");
  GLADE_HOOKUP_OBJECT (window1, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (window1, frame1, "frame1");
  GLADE_HOOKUP_OBJECT (window1, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (window1, label16, "label16");
  GLADE_HOOKUP_OBJECT (window1, arrow1, "arrow1");
  GLADE_HOOKUP_OBJECT (window1, image6, "image6");
  GLADE_HOOKUP_OBJECT (window1, label1, "label1");
  GLADE_HOOKUP_OBJECT (window1, label6, "label6");
  GLADE_HOOKUP_OBJECT (window1, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (window1, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (window1, hseparator1, "hseparator1");
  GLADE_HOOKUP_OBJECT (window1, hbuttonbox1, "hbuttonbox1");
  GLADE_HOOKUP_OBJECT (window1, button1, "button1");
  GLADE_HOOKUP_OBJECT (window1, button2, "button2");
  GLADE_HOOKUP_OBJECT (window1, button17, "button17");
  GLADE_HOOKUP_OBJECT_NO_REF (window1, tooltips, "tooltips");

  gtk_window_add_accel_group (GTK_WINDOW (window1), accel_group);

  return window1;
}

GtkWidget*
create_aboutdialog1 (void)
{
  GtkWidget *aboutdialog1;
  const gchar *authors[] = {
    "Ayub <mrayub@gmail.com>",
    NULL
  };
  /* TRANSLATORS: Replace this string with your names, one name per line. */
  gchar *translators = _("translator-credits");
  GdkPixbuf *aboutdialog1_logo_pixbuf;

  aboutdialog1 = gtk_about_dialog_new ();
  gtk_container_set_border_width (GTK_CONTAINER (aboutdialog1), 2);
  gtk_about_dialog_set_version (GTK_ABOUT_DIALOG (aboutdialog1), VERSION);
  gtk_about_dialog_set_name (GTK_ABOUT_DIALOG (aboutdialog1), _("\nAttendance Monitoring System\nVersion"));
  gtk_about_dialog_set_copyright (GTK_ABOUT_DIALOG (aboutdialog1), _("Copyright (c) 2006, Ayub <mrayub@gmail.com>"));
  gtk_about_dialog_set_authors (GTK_ABOUT_DIALOG (aboutdialog1), authors);
  gtk_about_dialog_set_translator_credits (GTK_ABOUT_DIALOG (aboutdialog1), translators);
  aboutdialog1_logo_pixbuf = create_pixbuf ("appicon_36x36.png");
  gtk_about_dialog_set_logo (GTK_ABOUT_DIALOG (aboutdialog1), aboutdialog1_logo_pixbuf);

  g_signal_connect ((gpointer) aboutdialog1, "delete_event",
                    G_CALLBACK (on_aboutdialog1_delete_event),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (aboutdialog1, aboutdialog1, "aboutdialog1");

  return aboutdialog1;
}

GtkWidget*
create_window2 (void)
{
  GtkWidget *window2;
  GdkPixbuf *window2_icon_pixbuf;
  GtkWidget *vbox2;
  GtkWidget *image3;
  GtkWidget *entry1;
  GtkWidget *label7;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  window2 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (window2, 350, -1);
  gtk_container_set_border_width (GTK_CONTAINER (window2), 5);
  gtk_window_set_title (GTK_WINDOW (window2), _("Barcode Entry"));
  gtk_window_set_position (GTK_WINDOW (window2), GTK_WIN_POS_CENTER);
  window2_icon_pixbuf = create_pixbuf ("appicon_36x36.png");
  if (window2_icon_pixbuf)
    {
      gtk_window_set_icon (GTK_WINDOW (window2), window2_icon_pixbuf);
      gdk_pixbuf_unref (window2_icon_pixbuf);
    }
  gtk_window_set_skip_taskbar_hint (GTK_WINDOW (window2), TRUE);
  gtk_window_set_type_hint (GTK_WINDOW (window2), GDK_WINDOW_TYPE_HINT_DIALOG);

  vbox2 = gtk_vbox_new (TRUE, 0);
  gtk_widget_show (vbox2);
  gtk_container_add (GTK_CONTAINER (window2), vbox2);

  image3 = create_pixmap (window2, "unknown_48x48.png");
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (vbox2), image3, TRUE, FALSE, 0);
  gtk_misc_set_padding (GTK_MISC (image3), 5, 5);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_box_pack_start (GTK_BOX (vbox2), entry1, TRUE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, entry1, _("Barcode Entry Field"), NULL);
  gtk_entry_set_max_length (GTK_ENTRY (entry1), 20);
  gtk_entry_set_visibility (GTK_ENTRY (entry1), FALSE);

  label7 = gtk_label_new (_("<b><span foreground=\"blue\">Show your ID</span></b>"));
  gtk_widget_show (label7);
  gtk_box_pack_start (GTK_BOX (vbox2), label7, TRUE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label7), TRUE);

  g_signal_connect ((gpointer) window2, "delete_event",
                    G_CALLBACK (on_window2_delete_event),
                    NULL);
  g_signal_connect ((gpointer) entry1, "activate",
                    G_CALLBACK (on_entry1_activate),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window2, window2, "window2");
  GLADE_HOOKUP_OBJECT (window2, vbox2, "vbox2");
  GLADE_HOOKUP_OBJECT (window2, image3, "image3");
  GLADE_HOOKUP_OBJECT (window2, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (window2, label7, "label7");
  GLADE_HOOKUP_OBJECT_NO_REF (window2, tooltips, "tooltips");

  return window2;
}

GtkWidget*
create_dialog1 (void)
{
  GtkWidget *dialog1;
  GdkPixbuf *dialog1_icon_pixbuf;
  GtkWidget *dialog_vbox1;
  GtkWidget *label8;
  GtkWidget *dialog_action_area1;
  GtkWidget *closebutton1;

  dialog1 = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (dialog1), _("Message"));
  gtk_window_set_position (GTK_WINDOW (dialog1), GTK_WIN_POS_CENTER);
  dialog1_icon_pixbuf = create_pixbuf ("appicon_36x36.png");
  if (dialog1_icon_pixbuf)
    {
      gtk_window_set_icon (GTK_WINDOW (dialog1), dialog1_icon_pixbuf);
      gdk_pixbuf_unref (dialog1_icon_pixbuf);
    }
  gtk_window_set_type_hint (GTK_WINDOW (dialog1), GDK_WINDOW_TYPE_HINT_DIALOG);

  dialog_vbox1 = GTK_DIALOG (dialog1)->vbox;
  gtk_widget_show (dialog_vbox1);

  label8 = gtk_label_new (_("Your messages will be here"));
  gtk_widget_show (label8);
  gtk_box_pack_start (GTK_BOX (dialog_vbox1), label8, TRUE, TRUE, 5);
  GTK_WIDGET_SET_FLAGS (label8, GTK_CAN_FOCUS);
  gtk_label_set_use_markup (GTK_LABEL (label8), TRUE);
  gtk_label_set_justify (GTK_LABEL (label8), GTK_JUSTIFY_CENTER);
  gtk_label_set_line_wrap (GTK_LABEL (label8), TRUE);
  gtk_label_set_selectable (GTK_LABEL (label8), TRUE);
  gtk_misc_set_padding (GTK_MISC (label8), 10, 10);

  dialog_action_area1 = GTK_DIALOG (dialog1)->action_area;
  gtk_widget_show (dialog_action_area1);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area1), GTK_BUTTONBOX_END);

  closebutton1 = gtk_button_new_from_stock ("gtk-close");
  gtk_widget_show (closebutton1);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog1), closebutton1, GTK_RESPONSE_CLOSE);
  GTK_WIDGET_SET_FLAGS (closebutton1, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) dialog1, "delete_event",
                    G_CALLBACK (on_dialog1_delete_event),
                    NULL);
  g_signal_connect ((gpointer) closebutton1, "clicked",
                    G_CALLBACK (on_closebutton1_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dialog1, dialog1, "dialog1");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog1, dialog_vbox1, "dialog_vbox1");
  GLADE_HOOKUP_OBJECT (dialog1, label8, "label8");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog1, dialog_action_area1, "dialog_action_area1");
  GLADE_HOOKUP_OBJECT (dialog1, closebutton1, "closebutton1");

  return dialog1;
}

GtkWidget*
create_window3 (void)
{
  GtkWidget *window3;
  GdkPixbuf *window3_icon_pixbuf;
  GtkWidget *vbox3;
  GtkWidget *image4;
  GtkWidget *label9;
  GtkWidget *hseparator2;
  GtkWidget *hbuttonbox2;
  GtkWidget *button4;
  GtkWidget *button5;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  window3 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window3), _("Message Window"));
  gtk_window_set_position (GTK_WINDOW (window3), GTK_WIN_POS_CENTER);
  window3_icon_pixbuf = create_pixbuf ("appicon_36x36.png");
  if (window3_icon_pixbuf)
    {
      gtk_window_set_icon (GTK_WINDOW (window3), window3_icon_pixbuf);
      gdk_pixbuf_unref (window3_icon_pixbuf);
    }
  gtk_window_set_skip_taskbar_hint (GTK_WINDOW (window3), TRUE);
  gtk_window_set_type_hint (GTK_WINDOW (window3), GDK_WINDOW_TYPE_HINT_DIALOG);

  vbox3 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox3);
  gtk_container_add (GTK_CONTAINER (window3), vbox3);

  image4 = gtk_image_new_from_stock ("gtk-dialog-question", GTK_ICON_SIZE_DIALOG);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (vbox3), image4, TRUE, TRUE, 0);

  label9 = gtk_label_new (_("label9"));
  gtk_widget_show (label9);
  gtk_box_pack_start (GTK_BOX (vbox3), label9, TRUE, TRUE, 10);
  gtk_label_set_use_markup (GTK_LABEL (label9), TRUE);
  gtk_label_set_justify (GTK_LABEL (label9), GTK_JUSTIFY_CENTER);
  gtk_misc_set_padding (GTK_MISC (label9), 5, 5);

  hseparator2 = gtk_hseparator_new ();
  gtk_widget_show (hseparator2);
  gtk_box_pack_start (GTK_BOX (vbox3), hseparator2, TRUE, TRUE, 0);

  hbuttonbox2 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox2);
  gtk_box_pack_start (GTK_BOX (vbox3), hbuttonbox2, TRUE, FALSE, 5);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox2), GTK_BUTTONBOX_SPREAD);

  button4 = gtk_button_new_from_stock ("gtk-no");
  gtk_widget_show (button4);
  gtk_container_add (GTK_CONTAINER (hbuttonbox2), button4);
  GTK_WIDGET_SET_FLAGS (button4, GTK_CAN_DEFAULT);
  gtk_tooltips_set_tip (tooltips, button4, _("If you don't agree"), NULL);

  button5 = gtk_button_new_from_stock ("gtk-yes");
  gtk_widget_show (button5);
  gtk_container_add (GTK_CONTAINER (hbuttonbox2), button5);
  GTK_WIDGET_SET_FLAGS (button5, GTK_CAN_DEFAULT);
  gtk_tooltips_set_tip (tooltips, button5, _("If you agree"), NULL);

  g_signal_connect ((gpointer) window3, "delete_event",
                    G_CALLBACK (on_window3_delete_event),
                    NULL);
  g_signal_connect ((gpointer) button4, "clicked",
                    G_CALLBACK (on_button4_clicked),
                    NULL);
  g_signal_connect ((gpointer) button5, "clicked",
                    G_CALLBACK (on_button5_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window3, window3, "window3");
  GLADE_HOOKUP_OBJECT (window3, vbox3, "vbox3");
  GLADE_HOOKUP_OBJECT (window3, image4, "image4");
  GLADE_HOOKUP_OBJECT (window3, label9, "label9");
  GLADE_HOOKUP_OBJECT (window3, hseparator2, "hseparator2");
  GLADE_HOOKUP_OBJECT (window3, hbuttonbox2, "hbuttonbox2");
  GLADE_HOOKUP_OBJECT (window3, button4, "button4");
  GLADE_HOOKUP_OBJECT (window3, button5, "button5");
  GLADE_HOOKUP_OBJECT_NO_REF (window3, tooltips, "tooltips");

  return window3;
}

GtkWidget*
create_window4 (void)
{
  GtkWidget *window4;
  GdkPixbuf *window4_icon_pixbuf;
  GtkWidget *vbox4;
  GtkWidget *fixed2;
  GtkWidget *frame4;
  GtkWidget *alignment5;
  GtkWidget *hbox3;
  GtkWidget *hpaned1;
  GtkWidget *fixed3;
  GtkWidget *entry2;
  GtkWidget *entry3;
  GtkWidget *textview2;
  GtkWidget *label14;
  GtkWidget *label13;
  GtkWidget *label15;
  GtkWidget *vbox5;
  GtkWidget *frame6;
  GtkWidget *alignment7;
  GtkWidget *image5;
  GtkWidget *label12;
  GtkWidget *hbuttonbox4;
  GtkWidget *button8;
  GtkWidget *button12;
  GtkWidget *label10;
  GtkWidget *hseparator3;
  GtkWidget *hbuttonbox3;
  GtkWidget *button6;
  GtkWidget *button7;
  GtkWidget *button11;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  window4 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window4), _("Stuff Information"));
  window4_icon_pixbuf = create_pixbuf ("appicon_36x36.png");
  if (window4_icon_pixbuf)
    {
      gtk_window_set_icon (GTK_WINDOW (window4), window4_icon_pixbuf);
      gdk_pixbuf_unref (window4_icon_pixbuf);
    }

  vbox4 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox4);
  gtk_container_add (GTK_CONTAINER (window4), vbox4);

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_box_pack_start (GTK_BOX (vbox4), fixed2, TRUE, TRUE, 0);

  frame4 = gtk_frame_new (NULL);
  gtk_widget_show (frame4);
  gtk_fixed_put (GTK_FIXED (fixed2), frame4, 24, 16);
  gtk_widget_set_size_request (frame4, 920, 536);

  alignment5 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (frame4), alignment5);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment5), 0, 0, 12, 0);

  hbox3 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox3);

  hpaned1 = gtk_hpaned_new ();
  gtk_widget_show (hpaned1);
  gtk_box_pack_start (GTK_BOX (hbox3), hpaned1, TRUE, TRUE, 0);
  gtk_paned_set_position (GTK_PANED (hpaned1), 1);

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_paned_pack1 (GTK_PANED (hpaned1), fixed3, TRUE, FALSE);

  entry2 = gtk_entry_new ();
  gtk_widget_show (entry2);
  gtk_fixed_put (GTK_FIXED (fixed3), entry2, 120, 24);
  gtk_widget_set_size_request (entry2, 158, 25);
  gtk_entry_set_max_length (GTK_ENTRY (entry2), 20);
  gtk_entry_set_visibility (GTK_ENTRY (entry2), FALSE);

  entry3 = gtk_entry_new ();
  gtk_widget_show (entry3);
  gtk_fixed_put (GTK_FIXED (fixed3), entry3, 120, 56);
  gtk_widget_set_size_request (entry3, 158, 25);

  textview2 = gtk_text_view_new ();
  gtk_widget_show (textview2);
  gtk_fixed_put (GTK_FIXED (fixed3), textview2, 120, 88);
  gtk_widget_set_size_request (textview2, 328, 208);
  gtk_container_set_border_width (GTK_CONTAINER (textview2), 2);
  gtk_tooltips_set_tip (tooltips, textview2, _("Additional meta information about stuff"), NULL);
  gtk_text_view_set_accepts_tab (GTK_TEXT_VIEW (textview2), FALSE);
  gtk_text_view_set_wrap_mode (GTK_TEXT_VIEW (textview2), GTK_WRAP_WORD);
  gtk_text_buffer_set_text (gtk_text_view_get_buffer (GTK_TEXT_VIEW (textview2)), _("Write additional information here..."), -1);

  label14 = gtk_label_new (_("<b>Name</b>"));
  gtk_widget_show (label14);
  gtk_fixed_put (GTK_FIXED (fixed3), label14, 0, 56);
  gtk_widget_set_size_request (label14, 112, 24);
  gtk_label_set_use_markup (GTK_LABEL (label14), TRUE);

  label13 = gtk_label_new (_("<b>Stuff ID</b>"));
  gtk_widget_show (label13);
  gtk_fixed_put (GTK_FIXED (fixed3), label13, 0, 24);
  gtk_widget_set_size_request (label13, 112, 24);
  gtk_label_set_use_markup (GTK_LABEL (label13), TRUE);

  label15 = gtk_label_new (_("<b>Meta Information</b>"));
  gtk_widget_show (label15);
  gtk_fixed_put (GTK_FIXED (fixed3), label15, 0, 88);
  gtk_widget_set_size_request (label15, 112, 24);
  gtk_label_set_use_markup (GTK_LABEL (label15), TRUE);

  vbox5 = gtk_vbox_new (FALSE, 5);
  gtk_widget_show (vbox5);
  gtk_paned_pack2 (GTK_PANED (hpaned1), vbox5, TRUE, FALSE);
  gtk_container_set_border_width (GTK_CONTAINER (vbox5), 2);

  frame6 = gtk_frame_new (NULL);
  gtk_widget_show (frame6);
  gtk_box_pack_start (GTK_BOX (vbox5), frame6, TRUE, TRUE, 0);

  alignment7 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (frame6), alignment7);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment7), 0, 0, 12, 0);

  image5 = create_pixmap (window4, "unknown.jpg");
  gtk_widget_show (image5);
  gtk_container_add (GTK_CONTAINER (alignment7), image5);

  label12 = gtk_label_new (_("<b>Photo</b>"));
  gtk_widget_show (label12);
  gtk_frame_set_label_widget (GTK_FRAME (frame6), label12);
  gtk_label_set_use_markup (GTK_LABEL (label12), TRUE);

  hbuttonbox4 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox4);
  gtk_box_pack_start (GTK_BOX (vbox5), hbuttonbox4, FALSE, FALSE, 0);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox4), GTK_BUTTONBOX_SPREAD);

  button8 = gtk_button_new_from_stock ("gtk-open");
  gtk_widget_show (button8);
  gtk_container_add (GTK_CONTAINER (hbuttonbox4), button8);
  GTK_WIDGET_SET_FLAGS (button8, GTK_CAN_DEFAULT);
  gtk_tooltips_set_tip (tooltips, button8, _("Load a photo"), NULL);

  button12 = gtk_button_new_from_stock ("gtk-remove");
  gtk_widget_show (button12);
  gtk_container_add (GTK_CONTAINER (hbuttonbox4), button12);
  GTK_WIDGET_SET_FLAGS (button12, GTK_CAN_DEFAULT);
  gtk_tooltips_set_tip (tooltips, button12, _("Remove photo"), NULL);

  label10 = gtk_label_new (_("<b>Stuff Infromation</b>"));
  gtk_widget_show (label10);
  gtk_frame_set_label_widget (GTK_FRAME (frame4), label10);
  gtk_label_set_use_markup (GTK_LABEL (label10), TRUE);

  hseparator3 = gtk_hseparator_new ();
  gtk_widget_show (hseparator3);
  gtk_box_pack_start (GTK_BOX (vbox4), hseparator3, FALSE, FALSE, 10);

  hbuttonbox3 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox3);
  gtk_box_pack_start (GTK_BOX (vbox4), hbuttonbox3, FALSE, FALSE, 5);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox3), GTK_BUTTONBOX_SPREAD);

  button6 = gtk_button_new_from_stock ("gtk-close");
  gtk_widget_show (button6);
  gtk_container_add (GTK_CONTAINER (hbuttonbox3), button6);
  GTK_WIDGET_SET_FLAGS (button6, GTK_CAN_DEFAULT);
  gtk_tooltips_set_tip (tooltips, button6, _("Unsaved changes will not be saved"), NULL);

  button7 = gtk_button_new_from_stock ("gtk-save");
  gtk_widget_show (button7);
  gtk_container_add (GTK_CONTAINER (hbuttonbox3), button7);
  GTK_WIDGET_SET_FLAGS (button7, GTK_CAN_DEFAULT);
  gtk_tooltips_set_tip (tooltips, button7, _("Save stuff information to database"), NULL);

  button11 = gtk_button_new_from_stock ("gtk-clear");
  gtk_widget_show (button11);
  gtk_container_add (GTK_CONTAINER (hbuttonbox3), button11);
  GTK_WIDGET_SET_FLAGS (button11, GTK_CAN_DEFAULT);
  gtk_tooltips_set_tip (tooltips, button11, _("Clear fields"), NULL);

  g_signal_connect ((gpointer) window4, "delete_event",
                    G_CALLBACK (on_window4_delete_event),
                    NULL);
  g_signal_connect ((gpointer) entry2, "activate",
                    G_CALLBACK (on_entry2_activate),
                    NULL);
  g_signal_connect ((gpointer) entry3, "activate",
                    G_CALLBACK (on_entry3_activate),
                    NULL);
  g_signal_connect ((gpointer) button8, "clicked",
                    G_CALLBACK (on_button8_clicked),
                    NULL);
  g_signal_connect ((gpointer) button12, "clicked",
                    G_CALLBACK (on_button12_clicked),
                    NULL);
  g_signal_connect ((gpointer) button6, "clicked",
                    G_CALLBACK (on_button6_clicked),
                    NULL);
  g_signal_connect ((gpointer) button7, "clicked",
                    G_CALLBACK (on_button7_clicked),
                    NULL);
  g_signal_connect ((gpointer) button11, "clicked",
                    G_CALLBACK (on_button11_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window4, window4, "window4");
  GLADE_HOOKUP_OBJECT (window4, vbox4, "vbox4");
  GLADE_HOOKUP_OBJECT (window4, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (window4, frame4, "frame4");
  GLADE_HOOKUP_OBJECT (window4, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (window4, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (window4, hpaned1, "hpaned1");
  GLADE_HOOKUP_OBJECT (window4, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (window4, entry2, "entry2");
  GLADE_HOOKUP_OBJECT (window4, entry3, "entry3");
  GLADE_HOOKUP_OBJECT (window4, textview2, "textview2");
  GLADE_HOOKUP_OBJECT (window4, label14, "label14");
  GLADE_HOOKUP_OBJECT (window4, label13, "label13");
  GLADE_HOOKUP_OBJECT (window4, label15, "label15");
  GLADE_HOOKUP_OBJECT (window4, vbox5, "vbox5");
  GLADE_HOOKUP_OBJECT (window4, frame6, "frame6");
  GLADE_HOOKUP_OBJECT (window4, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (window4, image5, "image5");
  GLADE_HOOKUP_OBJECT (window4, label12, "label12");
  GLADE_HOOKUP_OBJECT (window4, hbuttonbox4, "hbuttonbox4");
  GLADE_HOOKUP_OBJECT (window4, button8, "button8");
  GLADE_HOOKUP_OBJECT (window4, button12, "button12");
  GLADE_HOOKUP_OBJECT (window4, label10, "label10");
  GLADE_HOOKUP_OBJECT (window4, hseparator3, "hseparator3");
  GLADE_HOOKUP_OBJECT (window4, hbuttonbox3, "hbuttonbox3");
  GLADE_HOOKUP_OBJECT (window4, button6, "button6");
  GLADE_HOOKUP_OBJECT (window4, button7, "button7");
  GLADE_HOOKUP_OBJECT (window4, button11, "button11");
  GLADE_HOOKUP_OBJECT_NO_REF (window4, tooltips, "tooltips");

  gtk_widget_grab_default (button7);
  return window4;
}

GtkWidget*
create_filechooserdialog1 (void)
{
  GtkWidget *filechooserdialog1;
  GtkWidget *dialog_vbox2;
  GtkWidget *dialog_action_area2;
  GtkWidget *button9;
  GtkWidget *button10;

  filechooserdialog1 = gtk_file_chooser_dialog_new (_("Load file"), NULL, GTK_FILE_CHOOSER_ACTION_OPEN, NULL);
  gtk_window_set_type_hint (GTK_WINDOW (filechooserdialog1), GDK_WINDOW_TYPE_HINT_DIALOG);

  dialog_vbox2 = GTK_DIALOG (filechooserdialog1)->vbox;
  gtk_widget_show (dialog_vbox2);

  dialog_action_area2 = GTK_DIALOG (filechooserdialog1)->action_area;
  gtk_widget_show (dialog_action_area2);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area2), GTK_BUTTONBOX_END);

  button9 = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (button9);
  gtk_dialog_add_action_widget (GTK_DIALOG (filechooserdialog1), button9, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (button9, GTK_CAN_DEFAULT);

  button10 = gtk_button_new_from_stock ("gtk-open");
  gtk_widget_show (button10);
  gtk_dialog_add_action_widget (GTK_DIALOG (filechooserdialog1), button10, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (button10, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) filechooserdialog1, "delete_event",
                    G_CALLBACK (on_filechooserdialog1_delete_event),
                    NULL);
  g_signal_connect ((gpointer) button9, "clicked",
                    G_CALLBACK (on_button9_clicked),
                    NULL);
  g_signal_connect ((gpointer) button10, "clicked",
                    G_CALLBACK (on_button10_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (filechooserdialog1, filechooserdialog1, "filechooserdialog1");
  GLADE_HOOKUP_OBJECT_NO_REF (filechooserdialog1, dialog_vbox2, "dialog_vbox2");
  GLADE_HOOKUP_OBJECT_NO_REF (filechooserdialog1, dialog_action_area2, "dialog_action_area2");
  GLADE_HOOKUP_OBJECT (filechooserdialog1, button9, "button9");
  GLADE_HOOKUP_OBJECT (filechooserdialog1, button10, "button10");

  gtk_widget_grab_default (button10);
  return filechooserdialog1;
}

GtkWidget*
create_window5 (void)
{
  GtkWidget *window5;
  GdkPixbuf *window5_icon_pixbuf;
  GtkWidget *vbox6;
  GtkWidget *frame8;
  GtkWidget *alignment9;
  GtkWidget *fixed4;
  GtkWidget *hbuttonbox6;
  GtkWidget *button14;
  GtkWidget *frame9;
  GtkWidget *alignment10;
  GtkWidget *table1;
  GtkWidget *radiobutton1;
  GSList *radiobutton1_group = NULL;
  GtkWidget *radiobutton2;
  GtkWidget *hbox5;
  GtkWidget *comboboxentry3;
  GtkWidget *comboboxentry4;
  GtkWidget *hbox6;
  GtkWidget *comboboxentry5;
  GtkWidget *label19;
  GtkWidget *frame10;
  GtkWidget *alignment11;
  GtkWidget *table2;
  GtkWidget *label21;
  GtkWidget *entry7;
  GtkWidget *label20;
  GtkWidget *label18;
  GtkWidget *frame7;
  GtkWidget *alignment8;
  GtkWidget *scrolledwindow3;
  GtkWidget *treeview2;
  GtkWidget *label17;
  GtkWidget *hbuttonbox5;
  GtkWidget *button13;
  GtkWidget *button18;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  window5 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window5), _("Extended Query"));
  window5_icon_pixbuf = create_pixbuf ("appicon_36x36.png");
  if (window5_icon_pixbuf)
    {
      gtk_window_set_icon (GTK_WINDOW (window5), window5_icon_pixbuf);
      gdk_pixbuf_unref (window5_icon_pixbuf);
    }

  vbox6 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox6);
  gtk_container_add (GTK_CONTAINER (window5), vbox6);

  frame8 = gtk_frame_new (NULL);
  gtk_widget_show (frame8);
  gtk_box_pack_start (GTK_BOX (vbox6), frame8, FALSE, TRUE, 5);
  gtk_container_set_border_width (GTK_CONTAINER (frame8), 5);
  gtk_frame_set_label_align (GTK_FRAME (frame8), 0.5, 0.5);

  alignment9 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (frame8), alignment9);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment9), 0, 0, 12, 0);

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (alignment9), fixed4);
  gtk_container_set_border_width (GTK_CONTAINER (fixed4), 5);

  hbuttonbox6 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox6);
  gtk_fixed_put (GTK_FIXED (fixed4), hbuttonbox6, 300, 40);
  gtk_widget_set_size_request (hbuttonbox6, 85, 30);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox6), GTK_BUTTONBOX_SPREAD);

  button14 = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (button14);
  gtk_container_add (GTK_CONTAINER (hbuttonbox6), button14);
  GTK_WIDGET_SET_FLAGS (button14, GTK_CAN_DEFAULT);
  gtk_tooltips_set_tip (tooltips, button14, _("Run Query"), NULL);

  frame9 = gtk_frame_new (NULL);
  gtk_widget_show (frame9);
  gtk_fixed_put (GTK_FIXED (fixed4), frame9, 21, 8);
  gtk_widget_set_size_request (frame9, 214, 75);
  gtk_frame_set_shadow_type (GTK_FRAME (frame9), GTK_SHADOW_ETCHED_OUT);

  alignment10 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (frame9), alignment10);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment10), 0, 0, 12, 0);

  table1 = gtk_table_new (2, 2, FALSE);
  gtk_widget_show (table1);
  gtk_container_add (GTK_CONTAINER (alignment10), table1);
  gtk_container_set_border_width (GTK_CONTAINER (table1), 2);
  gtk_table_set_row_spacings (GTK_TABLE (table1), 2);
  gtk_table_set_col_spacings (GTK_TABLE (table1), 2);

  radiobutton1 = gtk_radio_button_new_with_mnemonic (NULL, _("Daily"));
  gtk_widget_show (radiobutton1);
  gtk_table_attach (GTK_TABLE (table1), radiobutton1, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton1), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton1));

  radiobutton2 = gtk_radio_button_new_with_mnemonic (NULL, _("Monthly"));
  gtk_widget_show (radiobutton2);
  gtk_table_attach (GTK_TABLE (table1), radiobutton2, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton2), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton2));

  hbox5 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox5);
  gtk_table_attach (GTK_TABLE (table1), hbox5, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  comboboxentry3 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry3);
  gtk_box_pack_start (GTK_BOX (hbox5), comboboxentry3, FALSE, TRUE, 0);
  gtk_widget_set_size_request (comboboxentry3, 60, -1);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("01"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("02"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("03"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("04"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("05"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("06"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("07"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("08"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("09"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("10"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("11"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("12"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("13"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("14"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("15"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("16"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("17"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("18"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("19"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("20"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("21"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("22"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("23"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("24"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("25"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("26"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("27"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("28"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("29"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("31"));
  gtk_combo_box_set_add_tearoffs (GTK_COMBO_BOX (comboboxentry3), TRUE);

  comboboxentry4 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry4);
  gtk_box_pack_start (GTK_BOX (hbox5), comboboxentry4, FALSE, TRUE, 0);
  gtk_widget_set_size_request (comboboxentry4, 60, -1);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry4), _("Jan"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry4), _("Feb"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry4), _("Mar"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry4), _("Apr"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry4), _("May"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry4), _("Jun"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry4), _("Jul"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry4), _("Aug"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry4), _("Sep"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry4), _("Oct"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry4), _("Nov"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry4), _("Dec"));
  gtk_combo_box_set_add_tearoffs (GTK_COMBO_BOX (comboboxentry4), TRUE);

  hbox6 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox6);
  gtk_table_attach (GTK_TABLE (table1), hbox6, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  comboboxentry5 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry5);
  gtk_box_pack_start (GTK_BOX (hbox6), comboboxentry5, FALSE, TRUE, 0);
  gtk_widget_set_size_request (comboboxentry5, 60, -1);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry5), _("Jan"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry5), _("Feb"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry5), _("Mar"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry5), _("Apr"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry5), _("May"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry5), _("Jun"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry5), _("Jul"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry5), _("Aug"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry5), _("Sep"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry5), _("Oct"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry5), _("Nov"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry5), _("Dec"));
  gtk_combo_box_set_add_tearoffs (GTK_COMBO_BOX (comboboxentry5), TRUE);

  label19 = gtk_label_new (_("<b>Time Options</b>"));
  gtk_widget_show (label19);
  gtk_frame_set_label_widget (GTK_FRAME (frame9), label19);
  gtk_label_set_use_markup (GTK_LABEL (label19), TRUE);

  frame10 = gtk_frame_new (NULL);
  gtk_widget_show (frame10);
  gtk_fixed_put (GTK_FIXED (fixed4), frame10, 448, 16);
  gtk_widget_set_size_request (frame10, 235, 59);
  gtk_frame_set_shadow_type (GTK_FRAME (frame10), GTK_SHADOW_ETCHED_OUT);

  alignment11 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (frame10), alignment11);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment11), 0, 0, 12, 0);

  table2 = gtk_table_new (1, 2, FALSE);
  gtk_widget_show (table2);
  gtk_container_add (GTK_CONTAINER (alignment11), table2);
  gtk_container_set_border_width (GTK_CONTAINER (table2), 2);
  gtk_table_set_row_spacings (GTK_TABLE (table2), 2);
  gtk_table_set_col_spacings (GTK_TABLE (table2), 10);

  label21 = gtk_label_new (_("<b>Stuff ID</b>"));
  gtk_widget_show (label21);
  gtk_table_attach (GTK_TABLE (table2), label21, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_use_markup (GTK_LABEL (label21), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label21), 0, 0.5);

  entry7 = gtk_entry_new ();
  gtk_widget_show (entry7);
  gtk_table_attach (GTK_TABLE (table2), entry7, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_max_length (GTK_ENTRY (entry7), 15);
  gtk_entry_set_visibility (GTK_ENTRY (entry7), FALSE);
  gtk_entry_set_activates_default (GTK_ENTRY (entry7), TRUE);

  label20 = gtk_label_new (_("<b>Filter Options</b>"));
  gtk_widget_show (label20);
  gtk_frame_set_label_widget (GTK_FRAME (frame10), label20);
  gtk_label_set_use_markup (GTK_LABEL (label20), TRUE);

  label18 = gtk_label_new (_("<b>Extended Query</b>"));
  gtk_widget_show (label18);
  gtk_frame_set_label_widget (GTK_FRAME (frame8), label18);
  gtk_label_set_use_markup (GTK_LABEL (label18), TRUE);

  frame7 = gtk_frame_new (NULL);
  gtk_widget_show (frame7);
  gtk_box_pack_start (GTK_BOX (vbox6), frame7, TRUE, TRUE, 0);
  gtk_frame_set_label_align (GTK_FRAME (frame7), 0.5, 0.5);

  alignment8 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (frame7), alignment8);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment8), 0, 0, 12, 0);

  scrolledwindow3 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow3);
  gtk_container_add (GTK_CONTAINER (alignment8), scrolledwindow3);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow3), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow3), GTK_SHADOW_IN);

  treeview2 = gtk_tree_view_new ();
  gtk_widget_show (treeview2);
  gtk_container_add (GTK_CONTAINER (scrolledwindow3), treeview2);
  gtk_widget_set_size_request (treeview2, -1, 230);
  gtk_tree_view_set_rules_hint (GTK_TREE_VIEW (treeview2), TRUE);

  label17 = gtk_label_new (_("<b>Query Output</b>"));
  gtk_widget_show (label17);
  gtk_frame_set_label_widget (GTK_FRAME (frame7), label17);
  gtk_label_set_use_markup (GTK_LABEL (label17), TRUE);

  hbuttonbox5 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox5);
  gtk_box_pack_start (GTK_BOX (vbox6), hbuttonbox5, FALSE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbuttonbox5), 5);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox5), GTK_BUTTONBOX_SPREAD);

  button13 = gtk_button_new_from_stock ("gtk-close");
  gtk_widget_show (button13);
  gtk_container_add (GTK_CONTAINER (hbuttonbox5), button13);
  GTK_WIDGET_SET_FLAGS (button13, GTK_CAN_DEFAULT);
  gtk_tooltips_set_tip (tooltips, button13, _("Close window"), NULL);

  button18 = gtk_button_new_from_stock ("gtk-print");
  gtk_widget_show (button18);
  gtk_container_add (GTK_CONTAINER (hbuttonbox5), button18);
  GTK_WIDGET_SET_FLAGS (button18, GTK_CAN_DEFAULT);
  gtk_tooltips_set_tip (tooltips, button18, _("Print query output"), NULL);

  g_signal_connect ((gpointer) window5, "delete_event",
                    G_CALLBACK (on_window5_delete_event),
                    NULL);
  g_signal_connect ((gpointer) button14, "clicked",
                    G_CALLBACK (on_button14_clicked),
                    NULL);
  g_signal_connect ((gpointer) button13, "clicked",
                    G_CALLBACK (on_button13_clicked),
                    NULL);
  g_signal_connect ((gpointer) button18, "clicked",
                    G_CALLBACK (on_button18_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window5, window5, "window5");
  GLADE_HOOKUP_OBJECT (window5, vbox6, "vbox6");
  GLADE_HOOKUP_OBJECT (window5, frame8, "frame8");
  GLADE_HOOKUP_OBJECT (window5, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (window5, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (window5, hbuttonbox6, "hbuttonbox6");
  GLADE_HOOKUP_OBJECT (window5, button14, "button14");
  GLADE_HOOKUP_OBJECT (window5, frame9, "frame9");
  GLADE_HOOKUP_OBJECT (window5, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (window5, table1, "table1");
  GLADE_HOOKUP_OBJECT (window5, radiobutton1, "radiobutton1");
  GLADE_HOOKUP_OBJECT (window5, radiobutton2, "radiobutton2");
  GLADE_HOOKUP_OBJECT (window5, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (window5, comboboxentry3, "comboboxentry3");
  GLADE_HOOKUP_OBJECT (window5, comboboxentry4, "comboboxentry4");
  GLADE_HOOKUP_OBJECT (window5, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (window5, comboboxentry5, "comboboxentry5");
  GLADE_HOOKUP_OBJECT (window5, label19, "label19");
  GLADE_HOOKUP_OBJECT (window5, frame10, "frame10");
  GLADE_HOOKUP_OBJECT (window5, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (window5, table2, "table2");
  GLADE_HOOKUP_OBJECT (window5, label21, "label21");
  GLADE_HOOKUP_OBJECT (window5, entry7, "entry7");
  GLADE_HOOKUP_OBJECT (window5, label20, "label20");
  GLADE_HOOKUP_OBJECT (window5, label18, "label18");
  GLADE_HOOKUP_OBJECT (window5, frame7, "frame7");
  GLADE_HOOKUP_OBJECT (window5, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (window5, scrolledwindow3, "scrolledwindow3");
  GLADE_HOOKUP_OBJECT (window5, treeview2, "treeview2");
  GLADE_HOOKUP_OBJECT (window5, label17, "label17");
  GLADE_HOOKUP_OBJECT (window5, hbuttonbox5, "hbuttonbox5");
  GLADE_HOOKUP_OBJECT (window5, button13, "button13");
  GLADE_HOOKUP_OBJECT (window5, button18, "button18");
  GLADE_HOOKUP_OBJECT_NO_REF (window5, tooltips, "tooltips");

  gtk_widget_grab_default (button14);
  return window5;
}

GtkWidget*
create_window6 (void)
{
  GtkWidget *window6;
  GdkPixbuf *window6_icon_pixbuf;
  GtkWidget *vbox7;
  GtkWidget *frame11;
  GtkWidget *alignment12;
  GtkWidget *scrolledwindow4;
  GtkWidget *treeview3;
  GtkWidget *label23;
  GtkWidget *hbuttonbox7;
  GtkWidget *button15;
  GtkWidget *button16;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  window6 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window6), _("Unmindful Stuffs"));
  window6_icon_pixbuf = create_pixbuf ("appicon_36x36.png");
  if (window6_icon_pixbuf)
    {
      gtk_window_set_icon (GTK_WINDOW (window6), window6_icon_pixbuf);
      gdk_pixbuf_unref (window6_icon_pixbuf);
    }

  vbox7 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox7);
  gtk_container_add (GTK_CONTAINER (window6), vbox7);

  frame11 = gtk_frame_new (NULL);
  gtk_widget_show (frame11);
  gtk_box_pack_start (GTK_BOX (vbox7), frame11, TRUE, TRUE, 0);
  gtk_frame_set_label_align (GTK_FRAME (frame11), 0.5, 0.5);

  alignment12 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (frame11), alignment12);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment12), 0, 0, 12, 0);

  scrolledwindow4 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow4);
  gtk_container_add (GTK_CONTAINER (alignment12), scrolledwindow4);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow4), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow4), GTK_SHADOW_IN);

  treeview3 = gtk_tree_view_new ();
  gtk_widget_show (treeview3);
  gtk_container_add (GTK_CONTAINER (scrolledwindow4), treeview3);

  label23 = gtk_label_new (_("<b>Stuff List</b>"));
  gtk_widget_show (label23);
  gtk_frame_set_label_widget (GTK_FRAME (frame11), label23);
  gtk_label_set_use_markup (GTK_LABEL (label23), TRUE);

  hbuttonbox7 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox7);
  gtk_box_pack_start (GTK_BOX (vbox7), hbuttonbox7, FALSE, TRUE, 5);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox7), GTK_BUTTONBOX_SPREAD);
  gtk_box_set_spacing (GTK_BOX (hbuttonbox7), 10);

  button15 = gtk_button_new_from_stock ("gtk-close");
  gtk_widget_show (button15);
  gtk_container_add (GTK_CONTAINER (hbuttonbox7), button15);
  GTK_WIDGET_SET_FLAGS (button15, GTK_CAN_DEFAULT);
  gtk_tooltips_set_tip (tooltips, button15, _("Close Window"), NULL);

  button16 = gtk_button_new_from_stock ("gtk-refresh");
  gtk_widget_show (button16);
  gtk_container_add (GTK_CONTAINER (hbuttonbox7), button16);
  GTK_WIDGET_SET_FLAGS (button16, GTK_CAN_DEFAULT);
  gtk_tooltips_set_tip (tooltips, button16, _("Refresh List"), NULL);

  g_signal_connect ((gpointer) window6, "delete_event",
                    G_CALLBACK (on_window6_delete_event),
                    NULL);
  g_signal_connect ((gpointer) treeview3, "row_activated",
                    G_CALLBACK (on_treeview3_row_activated),
                    NULL);
  g_signal_connect ((gpointer) button15, "clicked",
                    G_CALLBACK (on_button15_clicked),
                    NULL);
  g_signal_connect ((gpointer) button16, "clicked",
                    G_CALLBACK (on_button16_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window6, window6, "window6");
  GLADE_HOOKUP_OBJECT (window6, vbox7, "vbox7");
  GLADE_HOOKUP_OBJECT (window6, frame11, "frame11");
  GLADE_HOOKUP_OBJECT (window6, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (window6, scrolledwindow4, "scrolledwindow4");
  GLADE_HOOKUP_OBJECT (window6, treeview3, "treeview3");
  GLADE_HOOKUP_OBJECT (window6, label23, "label23");
  GLADE_HOOKUP_OBJECT (window6, hbuttonbox7, "hbuttonbox7");
  GLADE_HOOKUP_OBJECT (window6, button15, "button15");
  GLADE_HOOKUP_OBJECT (window6, button16, "button16");
  GLADE_HOOKUP_OBJECT_NO_REF (window6, tooltips, "tooltips");

  return window6;
}

GtkWidget*
create_window7 (void)
{
  GtkWidget *window7;
  GdkPixbuf *window7_icon_pixbuf;
  GtkWidget *image7;

  window7 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window7), _("Attendance Monitoring System"));
  gtk_window_set_position (GTK_WINDOW (window7), GTK_WIN_POS_CENTER);
  gtk_window_set_modal (GTK_WINDOW (window7), TRUE);
  window7_icon_pixbuf = create_pixbuf ("appicon_36x36.png");
  if (window7_icon_pixbuf)
    {
      gtk_window_set_icon (GTK_WINDOW (window7), window7_icon_pixbuf);
      gdk_pixbuf_unref (window7_icon_pixbuf);
    }
  gtk_window_set_type_hint (GTK_WINDOW (window7), GDK_WINDOW_TYPE_HINT_SPLASHSCREEN);

  image7 = create_pixmap (window7, "splash-logo.png");
  gtk_widget_show (image7);
  gtk_container_add (GTK_CONTAINER (window7), image7);

  g_signal_connect ((gpointer) window7, "delete_event",
                    G_CALLBACK (gtk_widget_destroy),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window7, window7, "window7");
  GLADE_HOOKUP_OBJECT (window7, image7, "image7");

  return window7;
}

GtkWidget*
create_window8 (void)
{
  GtkWidget *window8;
  GdkPixbuf *window8_icon_pixbuf;
  GtkWidget *vbox8;
  GtkWidget *label24;
  GtkWidget *entry8;
  GtkWidget *hbuttonbox8;
  GtkWidget *button19;
  GtkWidget *button20;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  window8 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window8), _("Login Password"));
  gtk_window_set_position (GTK_WINDOW (window8), GTK_WIN_POS_CENTER);
  window8_icon_pixbuf = create_pixbuf ("appicon_36x36.png");
  if (window8_icon_pixbuf)
    {
      gtk_window_set_icon (GTK_WINDOW (window8), window8_icon_pixbuf);
      gdk_pixbuf_unref (window8_icon_pixbuf);
    }

  vbox8 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox8);
  gtk_container_add (GTK_CONTAINER (window8), vbox8);

  label24 = gtk_label_new (_("\n<b>Please Enter Login Password</b>\n"));
  gtk_widget_show (label24);
  gtk_box_pack_start (GTK_BOX (vbox8), label24, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label24), TRUE);
  gtk_misc_set_padding (GTK_MISC (label24), 10, 0);

  entry8 = gtk_entry_new ();
  gtk_widget_show (entry8);
  gtk_box_pack_start (GTK_BOX (vbox8), entry8, TRUE, TRUE, 5);
  gtk_tooltips_set_tip (tooltips, entry8, _("Enter password here"), NULL);
  gtk_entry_set_max_length (GTK_ENTRY (entry8), 10);
  gtk_entry_set_visibility (GTK_ENTRY (entry8), FALSE);
  gtk_entry_set_activates_default (GTK_ENTRY (entry8), TRUE);

  hbuttonbox8 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox8);
  gtk_box_pack_start (GTK_BOX (vbox8), hbuttonbox8, FALSE, FALSE, 0);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox8), GTK_BUTTONBOX_SPREAD);
  gtk_box_set_spacing (GTK_BOX (hbuttonbox8), 5);

  button19 = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (button19);
  gtk_container_add (GTK_CONTAINER (hbuttonbox8), button19);
  GTK_WIDGET_SET_FLAGS (button19, GTK_CAN_DEFAULT);

  button20 = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (button20);
  gtk_container_add (GTK_CONTAINER (hbuttonbox8), button20);
  GTK_WIDGET_SET_FLAGS (button20, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) window8, "delete_event",
                    G_CALLBACK (on_window8_delete_event),
                    NULL);
  g_signal_connect ((gpointer) button19, "clicked",
                    G_CALLBACK (on_button19_clicked),
                    NULL);
  g_signal_connect ((gpointer) button20, "clicked",
                    G_CALLBACK (on_button20_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window8, window8, "window8");
  GLADE_HOOKUP_OBJECT (window8, vbox8, "vbox8");
  GLADE_HOOKUP_OBJECT (window8, label24, "label24");
  GLADE_HOOKUP_OBJECT (window8, entry8, "entry8");
  GLADE_HOOKUP_OBJECT (window8, hbuttonbox8, "hbuttonbox8");
  GLADE_HOOKUP_OBJECT (window8, button19, "button19");
  GLADE_HOOKUP_OBJECT (window8, button20, "button20");
  GLADE_HOOKUP_OBJECT_NO_REF (window8, tooltips, "tooltips");

  gtk_widget_grab_focus (entry8);
  gtk_widget_grab_default (button20);
  return window8;
}

GtkWidget*
create_window9 (void)
{
  GtkWidget *window9;
  GdkPixbuf *window9_icon_pixbuf;
  GtkWidget *vbox9;
  GtkWidget *label25;
  GtkWidget *entry9;
  GtkWidget *hbuttonbox10;
  GtkWidget *button21;
  GtkWidget *button22;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  window9 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window9), _("Add Stuff Database Password"));
  window9_icon_pixbuf = create_pixbuf ("appicon_36x36.png");
  if (window9_icon_pixbuf)
    {
      gtk_window_set_icon (GTK_WINDOW (window9), window9_icon_pixbuf);
      gdk_pixbuf_unref (window9_icon_pixbuf);
    }

  vbox9 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox9);
  gtk_container_add (GTK_CONTAINER (window9), vbox9);

  label25 = gtk_label_new (_("\n<b>Please Enter Database Password for Add Stuff</b>\n"));
  gtk_widget_show (label25);
  gtk_box_pack_start (GTK_BOX (vbox9), label25, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label25), TRUE);
  gtk_misc_set_padding (GTK_MISC (label25), 10, 0);

  entry9 = gtk_entry_new ();
  gtk_widget_show (entry9);
  gtk_box_pack_start (GTK_BOX (vbox9), entry9, FALSE, FALSE, 5);
  gtk_tooltips_set_tip (tooltips, entry9, _("Enter add stuff password"), NULL);
  gtk_entry_set_max_length (GTK_ENTRY (entry9), 10);
  gtk_entry_set_visibility (GTK_ENTRY (entry9), FALSE);
  gtk_entry_set_activates_default (GTK_ENTRY (entry9), TRUE);

  hbuttonbox10 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox10);
  gtk_box_pack_start (GTK_BOX (vbox9), hbuttonbox10, FALSE, TRUE, 5);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox10), GTK_BUTTONBOX_SPREAD);

  button21 = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (button21);
  gtk_container_add (GTK_CONTAINER (hbuttonbox10), button21);
  GTK_WIDGET_SET_FLAGS (button21, GTK_CAN_DEFAULT);

  button22 = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (button22);
  gtk_container_add (GTK_CONTAINER (hbuttonbox10), button22);
  GTK_WIDGET_SET_FLAGS (button22, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) window9, "delete_event",
                    G_CALLBACK (on_window9_delete_event),
                    NULL);
  g_signal_connect ((gpointer) button21, "clicked",
                    G_CALLBACK (on_button21_clicked),
                    NULL);
  g_signal_connect ((gpointer) button22, "clicked",
                    G_CALLBACK (on_button22_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window9, window9, "window9");
  GLADE_HOOKUP_OBJECT (window9, vbox9, "vbox9");
  GLADE_HOOKUP_OBJECT (window9, label25, "label25");
  GLADE_HOOKUP_OBJECT (window9, entry9, "entry9");
  GLADE_HOOKUP_OBJECT (window9, hbuttonbox10, "hbuttonbox10");
  GLADE_HOOKUP_OBJECT (window9, button21, "button21");
  GLADE_HOOKUP_OBJECT (window9, button22, "button22");
  GLADE_HOOKUP_OBJECT_NO_REF (window9, tooltips, "tooltips");

  gtk_widget_grab_focus (entry9);
  gtk_widget_grab_default (button22);
  return window9;
}

GtkWidget*
create_window10 (void)
{
  GtkWidget *window10;
  GdkPixbuf *window10_icon_pixbuf;
  GtkWidget *label26;

  window10 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window10), _("Unlicensed Copy"));
  gtk_window_set_position (GTK_WINDOW (window10), GTK_WIN_POS_CENTER);
  gtk_window_set_default_size (GTK_WINDOW (window10), 640, 480);
  window10_icon_pixbuf = create_pixbuf ("appicon_36x36.png");
  if (window10_icon_pixbuf)
    {
      gtk_window_set_icon (GTK_WINDOW (window10), window10_icon_pixbuf);
      gdk_pixbuf_unref (window10_icon_pixbuf);
    }

  label26 = gtk_label_new (_("<span size=\"xx-large\"><b>Unauthorized Copy!\nPlease collect a licensed copy.</b></span>"));
  gtk_widget_show (label26);
  gtk_container_add (GTK_CONTAINER (window10), label26);
  gtk_label_set_use_markup (GTK_LABEL (label26), TRUE);
  gtk_label_set_justify (GTK_LABEL (label26), GTK_JUSTIFY_CENTER);
  gtk_label_set_line_wrap (GTK_LABEL (label26), TRUE);

  g_signal_connect ((gpointer) window10, "delete_event",
                    G_CALLBACK (gtk_main_quit),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window10, window10, "window10");
  GLADE_HOOKUP_OBJECT (window10, label26, "label26");

  return window10;
}

GtkWidget*
create_window11 (void)
{
  GtkWidget *window11;
  GdkPixbuf *window11_icon_pixbuf;
  GtkWidget *vbox10;
  GtkWidget *label27;
  GtkWidget *entry10;
  GtkWidget *hbuttonbox11;
  GtkWidget *button23;
  GtkWidget *button24;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  window11 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window11), _("Edit Stuff Database Password"));
  window11_icon_pixbuf = create_pixbuf ("appicon_36x36.png");
  if (window11_icon_pixbuf)
    {
      gtk_window_set_icon (GTK_WINDOW (window11), window11_icon_pixbuf);
      gdk_pixbuf_unref (window11_icon_pixbuf);
    }

  vbox10 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox10);
  gtk_container_add (GTK_CONTAINER (window11), vbox10);

  label27 = gtk_label_new (_("\n<b>Please Enter Database Password for Edit Stuff</b>\n"));
  gtk_widget_show (label27);
  gtk_box_pack_start (GTK_BOX (vbox10), label27, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label27), TRUE);
  gtk_misc_set_padding (GTK_MISC (label27), 10, 0);

  entry10 = gtk_entry_new ();
  gtk_widget_show (entry10);
  gtk_box_pack_start (GTK_BOX (vbox10), entry10, FALSE, FALSE, 5);
  gtk_tooltips_set_tip (tooltips, entry10, _("Enter edit stuff password"), NULL);
  gtk_entry_set_max_length (GTK_ENTRY (entry10), 10);
  gtk_entry_set_visibility (GTK_ENTRY (entry10), FALSE);
  gtk_entry_set_activates_default (GTK_ENTRY (entry10), TRUE);

  hbuttonbox11 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox11);
  gtk_box_pack_start (GTK_BOX (vbox10), hbuttonbox11, FALSE, TRUE, 5);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox11), GTK_BUTTONBOX_SPREAD);

  button23 = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (button23);
  gtk_container_add (GTK_CONTAINER (hbuttonbox11), button23);
  GTK_WIDGET_SET_FLAGS (button23, GTK_CAN_DEFAULT);

  button24 = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (button24);
  gtk_container_add (GTK_CONTAINER (hbuttonbox11), button24);
  GTK_WIDGET_SET_FLAGS (button24, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) window11, "delete_event",
                    G_CALLBACK (on_window11_delete_event),
                    NULL);
  g_signal_connect ((gpointer) button23, "clicked",
                    G_CALLBACK (on_button23_clicked),
                    NULL);
  g_signal_connect ((gpointer) button24, "clicked",
                    G_CALLBACK (on_button24_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window11, window11, "window11");
  GLADE_HOOKUP_OBJECT (window11, vbox10, "vbox10");
  GLADE_HOOKUP_OBJECT (window11, label27, "label27");
  GLADE_HOOKUP_OBJECT (window11, entry10, "entry10");
  GLADE_HOOKUP_OBJECT (window11, hbuttonbox11, "hbuttonbox11");
  GLADE_HOOKUP_OBJECT (window11, button23, "button23");
  GLADE_HOOKUP_OBJECT (window11, button24, "button24");
  GLADE_HOOKUP_OBJECT_NO_REF (window11, tooltips, "tooltips");

  gtk_widget_grab_focus (entry10);
  gtk_widget_grab_default (button24);
  return window11;
}

GtkWidget*
create_window12 (void)
{
  GtkWidget *window12;
  GtkWidget *vbox11;
  GtkWidget *frame12;
  GtkWidget *alignment13;
  GtkWidget *fixed5;
  GtkWidget *frame13;
  GtkWidget *alignment14;
  GtkWidget *table3;
  GtkWidget *radiobutton3;
  GSList *radiobutton3_group = NULL;
  GtkWidget *radiobutton4;
  GtkWidget *hbox7;
  GtkWidget *comboboxentry6;
  GtkWidget *comboboxentry7;
  GtkWidget *hbox8;
  GtkWidget *comboboxentry8;
  GtkWidget *label28;
  GtkWidget *frame14;
  GtkWidget *alignment15;
  GtkWidget *table4;
  GtkWidget *label29;
  GtkWidget *entry11;
  GtkWidget *label30;
  GtkWidget *hbuttonbox12;
  GtkWidget *button25;
  GtkWidget *label31;
  GtkWidget *frame15;
  GtkWidget *alignment16;
  GtkWidget *scrolledwindow5;
  GtkWidget *treeview4;
  GtkWidget *label32;
  GtkWidget *hbuttonbox13;
  GtkWidget *button26;
  GtkWidget *button27;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  window12 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window12), _("First IN Last OUT"));

  vbox11 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox11);
  gtk_container_add (GTK_CONTAINER (window12), vbox11);

  frame12 = gtk_frame_new (NULL);
  gtk_widget_show (frame12);
  gtk_box_pack_start (GTK_BOX (vbox11), frame12, FALSE, TRUE, 5);
  gtk_container_set_border_width (GTK_CONTAINER (frame12), 5);
  gtk_frame_set_label_align (GTK_FRAME (frame12), 0.5, 0.5);

  alignment13 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (frame12), alignment13);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment13), 0, 0, 12, 0);

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (alignment13), fixed5);
  gtk_container_set_border_width (GTK_CONTAINER (fixed5), 5);

  frame13 = gtk_frame_new (NULL);
  gtk_widget_show (frame13);
  gtk_fixed_put (GTK_FIXED (fixed5), frame13, 21, 8);
  gtk_widget_set_size_request (frame13, 214, 75);
  gtk_frame_set_shadow_type (GTK_FRAME (frame13), GTK_SHADOW_ETCHED_OUT);

  alignment14 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (frame13), alignment14);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment14), 0, 0, 12, 0);

  table3 = gtk_table_new (2, 2, FALSE);
  gtk_widget_show (table3);
  gtk_container_add (GTK_CONTAINER (alignment14), table3);
  gtk_container_set_border_width (GTK_CONTAINER (table3), 2);
  gtk_table_set_row_spacings (GTK_TABLE (table3), 2);
  gtk_table_set_col_spacings (GTK_TABLE (table3), 2);

  radiobutton3 = gtk_radio_button_new_with_mnemonic (NULL, _("Daily"));
  gtk_widget_show (radiobutton3);
  gtk_table_attach (GTK_TABLE (table3), radiobutton3, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton3), radiobutton3_group);
  radiobutton3_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton3));

  radiobutton4 = gtk_radio_button_new_with_mnemonic (NULL, _("Monthly"));
  gtk_widget_show (radiobutton4);
  gtk_table_attach (GTK_TABLE (table3), radiobutton4, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton4), radiobutton3_group);
  radiobutton3_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton4));

  hbox7 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox7);
  gtk_table_attach (GTK_TABLE (table3), hbox7, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  comboboxentry6 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry6);
  gtk_box_pack_start (GTK_BOX (hbox7), comboboxentry6, FALSE, TRUE, 0);
  gtk_widget_set_size_request (comboboxentry6, 60, -1);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry6), _("01"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry6), _("02"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry6), _("03"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry6), _("04"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry6), _("05"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry6), _("06"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry6), _("07"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry6), _("08"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry6), _("09"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry6), _("10"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry6), _("11"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry6), _("12"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry6), _("13"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry6), _("14"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry6), _("15"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry6), _("16"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry6), _("17"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry6), _("18"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry6), _("19"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry6), _("20"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry6), _("21"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry6), _("22"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry6), _("23"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry6), _("24"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry6), _("25"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry6), _("26"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry6), _("27"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry6), _("28"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry6), _("29"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry6), _("30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry6), _("31"));
  gtk_combo_box_set_add_tearoffs (GTK_COMBO_BOX (comboboxentry6), TRUE);

  comboboxentry7 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry7);
  gtk_box_pack_start (GTK_BOX (hbox7), comboboxentry7, FALSE, TRUE, 0);
  gtk_widget_set_size_request (comboboxentry7, 60, -1);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry7), _("Jan"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry7), _("Feb"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry7), _("Mar"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry7), _("Apr"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry7), _("May"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry7), _("Jun"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry7), _("Jul"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry7), _("Aug"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry7), _("Sep"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry7), _("Oct"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry7), _("Nov"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry7), _("Dec"));
  gtk_combo_box_set_add_tearoffs (GTK_COMBO_BOX (comboboxentry7), TRUE);

  hbox8 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox8);
  gtk_table_attach (GTK_TABLE (table3), hbox8, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  comboboxentry8 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry8);
  gtk_box_pack_start (GTK_BOX (hbox8), comboboxentry8, FALSE, TRUE, 0);
  gtk_widget_set_size_request (comboboxentry8, 60, -1);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry8), _("Jan"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry8), _("Feb"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry8), _("Mar"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry8), _("Apr"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry8), _("May"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry8), _("Jun"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry8), _("Jul"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry8), _("Aug"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry8), _("Sep"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry8), _("Oct"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry8), _("Nov"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry8), _("Dec"));
  gtk_combo_box_set_add_tearoffs (GTK_COMBO_BOX (comboboxentry8), TRUE);

  label28 = gtk_label_new (_("<b>Time Options</b>"));
  gtk_widget_show (label28);
  gtk_frame_set_label_widget (GTK_FRAME (frame13), label28);
  gtk_label_set_use_markup (GTK_LABEL (label28), TRUE);

  frame14 = gtk_frame_new (NULL);
  gtk_widget_show (frame14);
  gtk_fixed_put (GTK_FIXED (fixed5), frame14, 448, 16);
  gtk_widget_set_size_request (frame14, 235, 59);
  gtk_frame_set_shadow_type (GTK_FRAME (frame14), GTK_SHADOW_ETCHED_OUT);

  alignment15 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (frame14), alignment15);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment15), 0, 0, 12, 0);

  table4 = gtk_table_new (1, 2, FALSE);
  gtk_widget_show (table4);
  gtk_container_add (GTK_CONTAINER (alignment15), table4);
  gtk_container_set_border_width (GTK_CONTAINER (table4), 2);
  gtk_table_set_row_spacings (GTK_TABLE (table4), 2);
  gtk_table_set_col_spacings (GTK_TABLE (table4), 10);

  label29 = gtk_label_new (_("<b>Stuff ID</b>"));
  gtk_widget_show (label29);
  gtk_table_attach (GTK_TABLE (table4), label29, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_use_markup (GTK_LABEL (label29), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label29), 0, 0.5);

  entry11 = gtk_entry_new ();
  gtk_widget_show (entry11);
  gtk_table_attach (GTK_TABLE (table4), entry11, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_max_length (GTK_ENTRY (entry11), 15);
  gtk_entry_set_visibility (GTK_ENTRY (entry11), FALSE);
  gtk_entry_set_activates_default (GTK_ENTRY (entry11), TRUE);

  label30 = gtk_label_new (_("<b>Filter Options</b>"));
  gtk_widget_show (label30);
  gtk_frame_set_label_widget (GTK_FRAME (frame14), label30);
  gtk_label_set_use_markup (GTK_LABEL (label30), TRUE);

  hbuttonbox12 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox12);
  gtk_fixed_put (GTK_FIXED (fixed5), hbuttonbox12, 300, 40);
  gtk_widget_set_size_request (hbuttonbox12, 85, 30);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox12), GTK_BUTTONBOX_SPREAD);

  button25 = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (button25);
  gtk_container_add (GTK_CONTAINER (hbuttonbox12), button25);
  GTK_WIDGET_SET_FLAGS (button25, GTK_CAN_DEFAULT);
  gtk_tooltips_set_tip (tooltips, button25, _("Run Query"), NULL);

  label31 = gtk_label_new (_("<b>First IN Last OUT Query</b>"));
  gtk_widget_show (label31);
  gtk_frame_set_label_widget (GTK_FRAME (frame12), label31);
  gtk_label_set_use_markup (GTK_LABEL (label31), TRUE);

  frame15 = gtk_frame_new (NULL);
  gtk_widget_show (frame15);
  gtk_box_pack_start (GTK_BOX (vbox11), frame15, TRUE, TRUE, 0);
  gtk_frame_set_label_align (GTK_FRAME (frame15), 0.5, 0.5);

  alignment16 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (frame15), alignment16);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment16), 0, 0, 12, 0);

  scrolledwindow5 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow5);
  gtk_container_add (GTK_CONTAINER (alignment16), scrolledwindow5);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow5), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow5), GTK_SHADOW_IN);

  treeview4 = gtk_tree_view_new ();
  gtk_widget_show (treeview4);
  gtk_container_add (GTK_CONTAINER (scrolledwindow5), treeview4);
  gtk_widget_set_size_request (treeview4, -1, 230);
  gtk_tree_view_set_rules_hint (GTK_TREE_VIEW (treeview4), TRUE);

  label32 = gtk_label_new (_("<b>Query Output</b>"));
  gtk_widget_show (label32);
  gtk_frame_set_label_widget (GTK_FRAME (frame15), label32);
  gtk_label_set_use_markup (GTK_LABEL (label32), TRUE);

  hbuttonbox13 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox13);
  gtk_box_pack_start (GTK_BOX (vbox11), hbuttonbox13, FALSE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbuttonbox13), 5);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox13), GTK_BUTTONBOX_SPREAD);

  button26 = gtk_button_new_from_stock ("gtk-close");
  gtk_widget_show (button26);
  gtk_container_add (GTK_CONTAINER (hbuttonbox13), button26);
  GTK_WIDGET_SET_FLAGS (button26, GTK_CAN_DEFAULT);
  gtk_tooltips_set_tip (tooltips, button26, _("Close window"), NULL);

  button27 = gtk_button_new_from_stock ("gtk-print");
  gtk_widget_show (button27);
  gtk_container_add (GTK_CONTAINER (hbuttonbox13), button27);
  GTK_WIDGET_SET_FLAGS (button27, GTK_CAN_DEFAULT);
  gtk_tooltips_set_tip (tooltips, button27, _("Print query output"), NULL);

  g_signal_connect ((gpointer) window12, "delete_event",
                    G_CALLBACK (on_window12_delete_event),
                    NULL);
  g_signal_connect ((gpointer) button25, "clicked",
                    G_CALLBACK (on_button25_clicked),
                    NULL);
  g_signal_connect ((gpointer) button26, "clicked",
                    G_CALLBACK (on_button26_clicked),
                    NULL);
  g_signal_connect ((gpointer) button27, "clicked",
                    G_CALLBACK (on_button27_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window12, window12, "window12");
  GLADE_HOOKUP_OBJECT (window12, vbox11, "vbox11");
  GLADE_HOOKUP_OBJECT (window12, frame12, "frame12");
  GLADE_HOOKUP_OBJECT (window12, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (window12, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (window12, frame13, "frame13");
  GLADE_HOOKUP_OBJECT (window12, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (window12, table3, "table3");
  GLADE_HOOKUP_OBJECT (window12, radiobutton3, "radiobutton3");
  GLADE_HOOKUP_OBJECT (window12, radiobutton4, "radiobutton4");
  GLADE_HOOKUP_OBJECT (window12, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (window12, comboboxentry6, "comboboxentry6");
  GLADE_HOOKUP_OBJECT (window12, comboboxentry7, "comboboxentry7");
  GLADE_HOOKUP_OBJECT (window12, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (window12, comboboxentry8, "comboboxentry8");
  GLADE_HOOKUP_OBJECT (window12, label28, "label28");
  GLADE_HOOKUP_OBJECT (window12, frame14, "frame14");
  GLADE_HOOKUP_OBJECT (window12, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (window12, table4, "table4");
  GLADE_HOOKUP_OBJECT (window12, label29, "label29");
  GLADE_HOOKUP_OBJECT (window12, entry11, "entry11");
  GLADE_HOOKUP_OBJECT (window12, label30, "label30");
  GLADE_HOOKUP_OBJECT (window12, hbuttonbox12, "hbuttonbox12");
  GLADE_HOOKUP_OBJECT (window12, button25, "button25");
  GLADE_HOOKUP_OBJECT (window12, label31, "label31");
  GLADE_HOOKUP_OBJECT (window12, frame15, "frame15");
  GLADE_HOOKUP_OBJECT (window12, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (window12, scrolledwindow5, "scrolledwindow5");
  GLADE_HOOKUP_OBJECT (window12, treeview4, "treeview4");
  GLADE_HOOKUP_OBJECT (window12, label32, "label32");
  GLADE_HOOKUP_OBJECT (window12, hbuttonbox13, "hbuttonbox13");
  GLADE_HOOKUP_OBJECT (window12, button26, "button26");
  GLADE_HOOKUP_OBJECT (window12, button27, "button27");
  GLADE_HOOKUP_OBJECT_NO_REF (window12, tooltips, "tooltips");

  gtk_widget_grab_default (button25);
  return window12;
}

