/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

#include "myfuncs.h"

int
main (int argc, char *argv[])
{
//  GtkWidget *window1;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

#ifndef _WIN32
  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");
#endif
  add_pixmap_directory ("../pixmaps");
//  add_pixmap_directory ("");
  add_pixmap_directory ("../share/pixmaps/attendence");

  /* load custom theme */
  gtk_rc_add_default_file("theme.default/gtk-2.0/gtkrc");

#ifdef _WIN32
#ifndef _DEBUG_
  freopen(LOGFILE, "w", stdout);
  freopen(ERRFILE, "w", stderr);
  FreeConsole(); /* leave the console */
#endif
#endif

  /*
   * available command line options:
   * --print-handler=<program-name>
   * --talk-handler=<program-name>
   * --noblock		// don't block on external command [only in *NIX]
   * --export-query
   * <program-name> will be invoked when 'print' button is clicked
   */
  int print_handler_defined = 0; /* print handler defined? */
  int i;

  should_block = 1;	/* block by default */
  should_export_query = 0; /* don't export query by default */
  talk_handler_defined = 0;
  for (i = 1; i < argc; i++) {
    if (!strncmp(argv[i], "--print-handler=", 16)) {
      sscanf(argv[i], "--print-handler=%s", print_handler);
      fprintf(stderr, "print_handler = %s\n", print_handler);
      print_handler_defined = 1;
    } else if (!strncmp(argv[i], "--talk-handler=", 15)) {
      sscanf(argv[i], "--talk-handler=%s", talk_handler);
      fprintf(stderr, "talk_handler = %s\n", talk_handler);
      talk_handler_defined = 1;
    } else if (!strncmp(argv[i], "--noblock", 9)) {
      should_block = 0;
    } else if (!strncmp(argv[i], "--export-query", 14)) {
      should_export_query = 1;
    }
  }

  if (!print_handler_defined) { /* take default action */
#ifdef _WIN32
    strcpy(print_handler, "print-doc");
#else
    strcpy(print_handler, "lpr");
#endif
  }
  if (!talk_handler_defined) { /* take default action */
#ifdef _WIN32
    strcpy(talk_handler, "say-it");
#else
    strcpy(talk_handler, "./say-it.sh");
#endif
  }
  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  /*
  window1 = create_window1 ();
  gtk_widget_show (window1);
  */
  init_env();
  ask_for_master_pass();
//  runproject(); /* defined in myfuncs.c */

  gtk_main ();
  return 0;
}

